apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: {{.Values.namespace}}
data:
  master.cnf: |
    [mysqld]
    server-id = 1
    log-bin = mysql-bin
    binlog-format = ROW
    gtid_mode = ON
    enforce_gtid_consistency = true
    log_replica_updates = ON
    binlog_checksum = NONE

    # Performance tuning
    innodb_flush_log_at_trx_commit = 1
    sync_binlog = 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kraken-db-sync-config
  namespace: {{.Values.namespace}}
data:
  # Database configuration
  DB_HOST: "kraken-db.kraken.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_NAME: "kraken"

  PLUGIN_FILE: "plugin_metadata.json"
  PACK_FILE: "plugin_packs.json"

  # Application settings
  DRY_RUN: "false"