apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: {{.Values.namespace}}
data:
  master.cnf: |
    [mysqld]
    server-id = 1
    log-bin = mysql-bin
    binlog-format = ROW
    gtid_mode = ON
    enforce_gtid_consistency = true
    log_replica_updates = ON
    binlog_checksum = NONE

    # Performance tuning
    innodb_flush_log_at_trx_commit = 1
    sync_binlog = 1