apiVersion: batch/v1
kind: Job
metadata:
  name: kraken-db-sync
  namespace: {{.Values.namespace}}
  labels:
    app: kraken-db-sync
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: kraken-db-sync
    spec:
      restartPolicy: Never
      containers:
        - name: kraken-db-sync
          image: {{.Values.image.syncRepository}}:{{.Values.image.syncTag}}
          imagePullPolicy: Always
          command: ["./main"]
          args:
            - "-db-host=$(DB_HOST)"
            - "-db-port=$(DB_PORT)"
            - "-db-user=$(DB_USER)"
            - "-db-password=$(DB_PASSWORD)"
            - "-db-name=$(DB_NAME)"
            - "-dry-run=$(DRY_RUN)"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: kraken-db-sync-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: kraken-db-sync-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: kraken-db-sync-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: kraken-db-sync-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: DRY_RUN
              valueFrom:
                configMapKeyRef:
                  name: kraken-db-sync-config
                  key: DRY_RUN
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
