name: kraken-db
namespace: kraken
replicaCount: 1

pvc:
  size: 20Gi

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "9.2.0"
  # The db sync job image
  syncRepository: cbartram/kraken-db-sync
  syncTag: "0.0.1"

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 1Gi

volumes:
  - name: mysql-master-config
    configMap:
      name: mysql-master-config
  - name: db-storage
    persistentVolumeClaim:
      claimName: kraken-db-pvc-longhorn

volumeMounts:
  - name: db-storage
    mountPath: /var/lib/mysql
