apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.name}}-pvc
  namespace: {{.Values.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.pvc.size}}